# Model arguments
model_name_or_path: friendshipkim/Llama-3.1-8B-Instruct-pruned-h0.43-i0.43-a0.0-d0.0
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
dataset_mixer:
  friendshipkim/Infinity-Instruct-7M-en: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 16

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 10000
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
pre_filter_max_seq_length: 2000
max_steps: -1
num_train_epochs: 1
run_name: 8b_instruct_prune_h0.43-i0.43-a0.0-d0.0
output_dir: ./saved_models/8b_instruct_prune_h0.43-i0.43-a0.0-d0.0
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 5000
save_total_limit: 2
seed: 42
warmup_ratio: 0.01
completion_only: true
debug_mode: true